name: seam-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - plotly
  - tqdm
  - pip:
    - segyio
    - streamlit
